name: Build and Deploy Spring Boot WAR

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Perform Security Scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan,java,depscan"

      - name: Remove target directory
        run: rm -rf target/

      - name: Maven clean
        run: mvn clean

      - name: Build with Maven
        run: mvn -X package --file pom.xml

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: app-0.0.1-SNAPSHOT.jar
          path: target/app-0.0.1-SNAPSHOT.jar

      - name: List target directory contents
        run: ls -l target